/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package anteproyecto;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
/**
 *
 * @author ASUS
 */


public class FormularioCompraGUI extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCompraGUI
     */
    
    private Cliente cliente; // Cliente logueado
    private List<Producto> productosDisponibles;
    private List<MetodoPago> metodosPago;

    private JComboBox<Producto> comboProductos;
    private JTextField txtCantidad;
    private JComboBox<MetodoPago> comboMetodoPago;
    private JTextArea resultado;
    private JButton btnAgregarAlCarrito;
    private JButton btnComprar;
    

public FormularioCompraGUI(Cliente cliente, List<Producto> productos, List<MetodoPago> metodos) {
    initComponents();
    this.cliente = cliente;
    this.productosDisponibles = productos;
    this.metodosPago = metodos;

    setTitle("Formulario de Compra");
    setSize(500, 400);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setLayout(new GridLayout(7, 2, 5, 5));

    comboProductos = new JComboBox<>(productos.toArray(new Producto[0]));
    txtCantidad = new JTextField();
    comboMetodoPago = new JComboBox<>(metodos.toArray(new MetodoPago[0]));

    btnAgregarAlCarrito = new JButton("Agregar al carrito");
    btnComprar = new JButton("Comprar");
    


    resultado = new JTextArea();
    resultado.setEditable(false);
    JScrollPane scrollPane = new JScrollPane(resultado);

    add(new JLabel("Producto:"));
    add(comboProductos);

    add(new JLabel("Cantidad:"));
    add(txtCantidad);

    add(btnAgregarAlCarrito);
    add(new JLabel(""));

    add(new JLabel("Método de pago:"));
    add(comboMetodoPago);

    add(btnComprar);
    add(new JLabel(""));

    add(new JLabel("Resultado:"));
    add(scrollPane);

    btnAgregarAlCarrito.addActionListener(e -> agregarProductoAlCarrito());
    btnComprar.addActionListener(e -> realizarCompra());

    setVisible(true);
}

    
        private void agregarProductoAlCarrito() {
        try {
            Producto producto = (Producto) comboProductos.getSelectedItem();
            int cantidad = Integer.parseInt(txtCantidad.getText());

            if (!producto.hayStockSuficiente(cantidad)) {
                mostrarMensaje("Stock insuficiente para el producto seleccionado.");
                return;
            }

            cliente.getCarrito().agregarProducto(producto, cantidad);
            mostrarMensaje("Producto agregado al carrito.");

        } catch (NumberFormatException ex) {
            mostrarMensaje("Cantidad inválida.");
        }
    }
        
        private void realizarCompra() {
           MetodoPago metodo = (MetodoPago) comboMetodoPago.getSelectedItem();

        try {
            Venta venta = cliente.realizarVenta(metodo);
            mostrarMensaje("¡Compra realizada con éxito!\nTotal: $" + venta.calcularTotal());

        } catch (Exception ex) {
            mostrarMensaje("Error al realizar la compra: " + ex.getMessage());
        }
    }

    private void mostrarMensaje(String mensaje) {
        resultado.setText(mensaje);
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
            // Cierra la ventana actual
    this.dispose();

    // Abre la ventana de inicio
    SwingUtilities.invokeLater(() -> new VentanaInicioGUI().setVisible(true));
    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCalificacionGUI().setVisible(true);
            }
        }); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
