/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anteproyecto;
import javax.swing.*;
import java.awt.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author ASUS
 */
public class FormularioCalificacionGUI extends javax.swing.JFrame {

private String nombreUsuario;

    public FormularioCalificacionGUI() {
    }


    public FormularioCalificacionGUI(String nombre) {
        setTitle("Calificar Álbum");
        initComponents();
        setSize(1000, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        this.nombreUsuario = nombre;
    
        txtUsuario.setText(nombreUsuario); 
        resultado.setEditable(false);
        

        
        
        // Fuentes y colores base
Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 20);
Font fuenteTexto = new Font("Segoe UI", Font.PLAIN, 14);

Color azulOscuro = new Color(44, 62, 80);
Color grisOscuro = new Color(52, 73, 94);
Color fondoClaro = new Color(236, 240, 241);
Color verde = new Color(39, 174, 96);
Color rojo = new Color(192, 57, 43);
Color azul = new Color(41, 128, 185);

// Fondo general
getContentPane().setBackground(fondoClaro);

// Etiquetas


    titulo.setFont(fuenteTitulo);
    titulo.setForeground(new Color(44, 62, 80)); // Azul oscuro suave


NombreTitulo.setFont(fuenteTexto);
NombreTitulo.setForeground(azulOscuro);
jLabel1.setFont(fuenteTexto);
jLabel1.setForeground(grisOscuro);
jLabel2.setFont(fuenteTexto);
jLabel2.setForeground(grisOscuro);
jLabel3.setFont(fuenteTexto);
jLabel3.setForeground(grisOscuro);

// Campos de texto
txtAlbum.setFont(fuenteTexto);
txtUsuario.setFont(fuenteTexto);
txtCalificacion.setFont(fuenteTexto);
txtComentario.setFont(fuenteTexto);

// Área de resultado
resultado.setFont(new Font("Monospaced", Font.PLAIN, 13));
resultado.setBackground(new Color(248, 249, 250)); // gris muy claro
resultado.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
resultado.setForeground(Color.DARK_GRAY);

// Botones
btnEnviar.setFont(fuenteTexto);
btnEnviar.setBackground(verde);
btnEnviar.setForeground(Color.WHITE);
btnEnviar.setFocusPainted(false);

btnRegresar.setFont(fuenteTexto);
btnRegresar.setBackground(rojo);
btnRegresar.setForeground(Color.WHITE);
btnRegresar.setFocusPainted(false);

        
        setVisible(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        NombreTitulo = new javax.swing.JLabel();
        txtAlbum = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtCalificacion = new javax.swing.JTextField();
        txtComentario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        NombreTitulo.setText("Nombre del álbum:");
        getContentPane().add(NombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        txtAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlbumActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 120, 30));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 120, 30));
        getContentPane().add(txtCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 120, 30));
        getContentPane().add(txtComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 120, 30));

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 290, 320));

        jLabel1.setText("Tu nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel2.setText("Comentario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel3.setText("Calificacion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        titulo.setText("Queremos saber tu opinión");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    this.dispose();
    SwingUtilities.invokeLater(() -> new VentanaInicioGUI(nombreUsuario).setVisible(true));
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
    try {
        String album = txtAlbum.getText().trim();
        String usuario = txtUsuario.getText().trim();
        double calificacion = Double.parseDouble(txtCalificacion.getText().trim());
        String comentario = txtComentario.getText().trim();

        if (album.isEmpty() || usuario.isEmpty() || comentario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.",
                "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (calificacion < 1 || calificacion > 10) {
            JOptionPane.showMessageDialog(this, "La calificación debe estar entre 1 y 10.",
                "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ✅ Corregido: usar una instancia de CalificacionDAO
        new CalificacionDAO().insertarCalificacion(album, usuario, calificacion, comentario);

        resultado.append("Álbum: " + album + "\n"
            + "Usuario: " + usuario + "\n"
            + "Calificación: " + calificacion + "/10\n"
            + "Comentario: " + comentario + "\n"
            + "----------------------------------\n\n");

        JOptionPane.showMessageDialog(this, "Calificación guardada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        txtAlbum.setText("");
        txtUsuario.setText("");
        txtCalificacion.setText("");
        txtComentario.setText("");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Calificación inválida. Ingresa un número entre 1 y 10.",
            "Error", JOptionPane.WARNING_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos:\n" + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Look & feel (opcional)
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {

        }

        // Lanzar la GUI
        SwingUtilities.invokeLater(() -> new FormularioCalificacionGUI());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreTitulo;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
