/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package anteproyecto;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
/**
 *
 * @author ASUS
 */


public class FormularioCompraGUI extends javax.swing.JFrame {

    
    private Cliente cliente; // Cliente logueado
    private List<Producto> productosDisponibles;
    private List<MetodoPago> metodosPago;
    private String nombreUsuario;

    public FormularioCompraGUI() {
    }

    
public FormularioCompraGUI(Cliente cliente, List<Producto> productos, List<MetodoPago> metodos, String nombreUsuario) {
    setTitle("Compras");
    
    initComponents(); 
    
    this.nombreUsuario = nombreUsuario;
    this.cliente = cliente;
    this.productosDisponibles = productos;
    this.metodosPago = metodos;
    
    comboProductos.setModel(new DefaultComboBoxModel<Producto>());
        for (Producto p : productos) {
            ((DefaultComboBoxModel<Producto>) comboProductos.getModel()).addElement(p);
        }

    DefaultComboBoxModel<MetodoPago> modeloMetodo = new DefaultComboBoxModel<>();
        for (MetodoPago m : metodosPago) {
            modeloMetodo.addElement(m);
        }

    
    // Limpia los ítems del combo generado por NetBeans
    comboProductos.removeAllItems();
    for (Producto p : productosDisponibles) {
        comboProductos.addItem(p); // Esto mostrará toString() de Producto
    }

    // Limpia y carga productos
    comboProductos.removeAllItems();
    for (Producto p : productosDisponibles) {
        comboProductos.addItem(p);
    }

    // Limpia y carga métodos de pago
    comboMetodoPago.removeAllItems();
    for (MetodoPago m : metodosPago) {
        comboMetodoPago.addItem(m);
    }

    
    // Agregar listeners y lógica como ya lo hiciste

    resultado.setEditable(false);   
    
   

    btnAgregarAlCarrito.addActionListener(e -> agregarProductoAlCarrito());
    btnComprar.addActionListener(e -> realizarCompra());

    setSize(1000, 700);
    setLocationRelativeTo(null);
    setVisible(true);


}
    
        private void agregarProductoAlCarrito() {
        try {
            Producto producto = (Producto) comboProductos.getSelectedItem();
            int cantidad = Integer.parseInt(txtCantidad.getText());

            if (!producto.hayStockSuficiente(cantidad)) {
                mostrarMensaje("Stock insuficiente para el producto seleccionado.");
                return;
            }

            cliente.getCarrito().agregarProducto(producto, cantidad);
            mostrarMensaje("Producto agregado al carrito.");

        } catch (NumberFormatException ex) {
            mostrarMensaje("Cantidad inválida.");
        }
    }
        
        private void realizarCompra() {
           MetodoPago metodo = (MetodoPago) comboMetodoPago.getSelectedItem();
        try {
            Venta venta = cliente.realizarVenta(metodo);
            mostrarMensaje("¡Compra realizada con éxito!\nTotal: $" + venta.calcularTotal());

        } catch (Exception ex) {
            mostrarMensaje("Error al realizar la compra: " + ex.getMessage());
        }
    }

    private void mostrarMensaje(String mensaje) {
        resultado.setText(mensaje);
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboMetodoPago = new javax.swing.JComboBox();
        btnAgregarAlCarrito = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Artifakt Element Book", 1, 12)); // NOI18N
        jLabel1.setText("Compra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        comboProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductosActionPerformed(evt);
            }
        });
        getContentPane().add(comboProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 130, 30));

        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        comboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btnAgregarAlCarrito.setText("Agregar al carrito");
        btnAgregarAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarAlCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, -1, -1));

        btnComprar.setFont(new java.awt.Font("Artifakt Element Book", 1, 12)); // NOI18N
        btnComprar.setText("Comprar");
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, -1, -1));

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
    this.dispose();
    SwingUtilities.invokeLater(() -> new VentanaInicioGUI(nombreUsuario).setVisible(true));
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed

    }//GEN-LAST:event_comboProductosActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCalificacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCalificacionGUI().setVisible(true);
            }
        }); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox comboMetodoPago;
    private javax.swing.JComboBox comboProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
