/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anteproyecto;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class FormularioCalificacionGUI extends javax.swing.JFrame {

private String nombreUsuario;

    public FormularioCalificacionGUI() {
    }


    public FormularioCalificacionGUI(String nombre) {
        setTitle("Calificar Álbum");
        initComponents();
        setSize(1000, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        this.nombreUsuario = nombre;
    
        txtUsuario.setText(nombreUsuario); 
        resultado.setEditable(false);
        setVisible(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        NombreTitulo = new javax.swing.JLabel();
        txtAlbum = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtCalificacion = new javax.swing.JTextField();
        txtComentario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        NombreTitulo.setText("Nombre del álbum:");
        getContentPane().add(NombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        txtAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlbumActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 70, -1));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 70, -1));
        getContentPane().add(txtCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 70, -1));
        getContentPane().add(txtComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 70, -1));

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 290, 140));

        jLabel1.setText("Tu nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel2.setText("Comentario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel3.setText("Calificacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    this.dispose();
    SwingUtilities.invokeLater(() -> new VentanaInicioGUI(nombreUsuario).setVisible(true));
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
    try {
        String album = txtAlbum.getText().trim();
        String usuario = txtUsuario.getText().trim();
        double calificacion = Double.parseDouble(txtCalificacion.getText().trim());
        String comentario = txtComentario.getText().trim();

        if (album.isEmpty() || usuario.isEmpty() || comentario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        if (calificacion < 1 || calificacion > 10) {
            JOptionPane.showMessageDialog(this, "La calificación debe estar entre 1 y 10.");
            return;
        }

        resultado.setText("¡Gracias por tu calificación!\n\n"
                + "Álbum: " + album + "\n"
                + "Usuario: " + usuario + "\n"
                + "Calificación: " + calificacion + "/10\n"
                + "Comentario: " + comentario);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Calificación inválida. Ingresa un número entre 1 y 10.");
    }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Look & feel (opcional)
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            // Si falla, se ignora
        }

        // Lanzar la GUI
        SwingUtilities.invokeLater(() -> new FormularioCalificacionGUI());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreTitulo;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
