/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anteproyecto;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author ASUS
 */
public class FormularioCalificacionGUI extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCalificacionGUI
     */
    public FormularioCalificacionGUI() {
        setTitle("Calificar Álbum");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centra la ventana en pantalla
        setLayout(new GridLayout(6, 2, 5, 5));

        // Campos de entrada
        JTextField txtAlbum = new JTextField();
        JTextField txtUsuario = new JTextField();
        JTextField txtCalificacion = new JTextField();
        JTextField txtComentario = new JTextField();

        // Área de resultado
        JTextArea resultado = new JTextArea();
        resultado.setEditable(false);
        JScrollPane scrollResultado = new JScrollPane(resultado);

        // Botón
        JButton btnEnviar = new JButton("Enviar calificación");
        
        JButton btnRegresar = new JButton("Regresar al inicio");
        btnRegresar.addActionListener(e -> {
        dispose();
    SwingUtilities.invokeLater(() -> new VentanaInicioGUI());
});

add(btnRegresar);

        // Etiquetas y campos
        add(new JLabel("Nombre del álbum:"));
        add(txtAlbum);

        add(new JLabel("Tu nombre:"));
        add(txtUsuario);

        add(new JLabel("Calificación (1 a 5):"));
        add(txtCalificacion);

        add(new JLabel("Comentario:"));
        add(txtComentario);

        add(btnEnviar);
        add(new JLabel("")); // espacio vacío

        add(new JLabel("Resultado:"));
        add(scrollResultado);

        // Acción del botón
        btnEnviar.addActionListener(e -> {
            try {
                String album = txtAlbum.getText().trim();
                String usuario = txtUsuario.getText().trim();
                int calificacion = Integer.parseInt(txtCalificacion.getText().trim());
                String comentario = txtComentario.getText().trim();

                if (album.isEmpty() || usuario.isEmpty() || comentario.isEmpty()) {
                    resultado.setText("Por favor, completa todos los campos.");
                    return;
                }

                if (calificacion < 1 || calificacion > 5) {
                    resultado.setText("La calificación debe estar entre 1 y 5.");
                    return;
                }

                resultado.setText("¡Gracias por tu calificación!\n\n"
                        + "Álbum: " + album + "\n"
                        + "Usuario: " + usuario + "\n"
                        + "Calificación: " + calificacion + "/5\n"
                        + "Comentario: " + comentario);
            } catch (NumberFormatException ex) {
                resultado.setText("Calificación inválida. Ingresa un número entre 1 y 5.");
            }
        });

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Look & feel (opcional)
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            // Si falla, se ignora
        }

        // Lanzar la GUI
        SwingUtilities.invokeLater(() -> new FormularioCalificacionGUI());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
