/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anteproyecto;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
/**
 *
 * @author estudiante
 */
public class InicioRegistro extends javax.swing.JFrame {


    public InicioRegistro() {
        initComponents();
        setTitle("Auralia");
        setSize(1000, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        
    btnSiguiente.setBackground(new Color(74, 144, 226)); // Azul
    btnSiguiente.setForeground(Color.WHITE); // Texto blanco
    btnSiguiente.setFont(new Font("Segoe UI", Font.BOLD, 16));
    btnSiguiente.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
    
    jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 26));
    jLabel1.setForeground(new Color(51, 51, 51)); // Gris oscuro

    infoNombre.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    infoNombre.setBackground(new Color(255, 255, 255));
    infoNombre.setBorder(BorderFactory.createLineBorder(new Color(163, 194, 242), 2));

    
    setVisible(true);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        infoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        infoTelefono = new javax.swing.JTextField();
        infoDoc = new javax.swing.JTextField();
        infoCorreo = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingresa tu información");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, 20));

        infoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(infoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 170, 40));

        jLabel3.setText("Numero de telefono: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel4.setText("Correo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        infoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(infoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 170, 40));

        infoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoDocActionPerformed(evt);
            }
        });
        getContentPane().add(infoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 170, 40));

        infoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(infoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 170, 40));

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        jLabel5.setText("Numero de documento: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoNombreActionPerformed

    private void infoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoTelefonoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
    String nombre = infoNombre.getText().trim();
    String correo = infoCorreo.getText().trim();
    String doc = infoDoc.getText().trim();
    String tel = infoTelefono.getText().trim();

    if (nombre.isEmpty() || correo.isEmpty() || doc.isEmpty() || tel.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        return;
    }

    // Aquí podrías construir un objeto Cliente y pasarlo si lo deseas.
    new VentanaInicioGUI(nombre);
    this.dispose(); // Cierra esta ventana
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void infoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoDocActionPerformed

    private void infoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField infoCorreo;
    private javax.swing.JTextField infoDoc;
    private javax.swing.JTextField infoNombre;
    private javax.swing.JTextField infoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
