/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anteproyecto;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Arrays;
/**
 *
 * @author ASUS
 */
public class VentanaInicioGUI extends javax.swing.JFrame {
    private String nombreUsuario;

    public VentanaInicioGUI() {
    }
    
    
    public VentanaInicioGUI(String nombre) {
        this.nombreUsuario = nombre;
        initComponents();
        setSize(1000, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        jLabel1.setText("Bienvenido, " + nombre + "!");
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comprarBtn = new javax.swing.JButton();
        calificarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bienvenido.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel2.setText("¿Que deseas hacer?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        comprarBtn.setText("Comprar");
        comprarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(comprarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        calificarBtn.setText("Calificar");
        calificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calificarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBtnActionPerformed
             
        dispose(); // Cierra la ventana de inicio
        Rol rolCliente = new Rol(2, "Cliente", true);
        Cliente cliente = new Cliente(1, "Diego", "correo@correo", "contrasena", "123410", rolCliente);

        Producto vinilo1 = new Producto(1, "Vinilo - OK Computer", 120.0, true, 10);
        Producto vinilo2 = new Producto(2, "Vinilo - To Pimp a Butterfly", 150.0, true, 5);
        Producto cuadro = new Producto(3, "Cuadro Currents", 60.0, true, 3);

        MetodoPago pago1 = new MetodoPago(1, "Tarjeta débito");
        MetodoPago pago2 = new MetodoPago(2, "Tarjeta crédito");
            
        java.util.List<Producto> productos = Arrays.asList(vinilo1, vinilo2, cuadro);
        java.util.List<MetodoPago> metodos = Arrays.asList(pago1, pago2);
        String nombre = this.nombreUsuario;
        SwingUtilities.invokeLater(() -> new FormularioCompraGUI(cliente, productos, metodos, nombre));

        
    }//GEN-LAST:event_comprarBtnActionPerformed

    private void calificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calificarBtnActionPerformed
            dispose(); // Cierra la ventana de inicio
            SwingUtilities.invokeLater(() -> new FormularioCalificacionGUI().setVisible(true));
        
    }//GEN-LAST:event_calificarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new VentanaInicioGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calificarBtn;
    private javax.swing.JButton comprarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
